# -*- coding: utf-8 -*-
"""CV-CO1-AT1-Q08

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UtKPB27ftGBQYsCEi8aGyNau5a4P0o7W
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Step 1: Create a synthetic grayscale image
image = np.zeros((256, 256), dtype=np.uint8)
cv2.circle(image, (128, 128), 70, 200, -1)
cv2.rectangle(image, (40, 40), (80, 80), 120, -1)
cv2.line(image, (20, 220), (220, 20), 255, 3)

# Step 2: Add Gaussian Noise (Sensor Noise)
noise = np.random.normal(0, 25, image.shape).astype(np.int16)
noisy = np.clip(image.astype(np.int16) + noise, 0, 255).astype(np.uint8)

# Step 3: Reduce Noise using Gaussian Blur
denoised = cv2.GaussianBlur(noisy, (5,5), 1)

# Step 4: Display Images
plt.figure(figsize=(15,5))

plt.subplot(1,3,1)
plt.imshow(image, cmap='gray')
plt.title("Original Image")
plt.axis('off')

plt.subplot(1,3,2)
plt.imshow(noisy, cmap='gray')
plt.title("Noisy Image (Sensor Noise)")
plt.axis('off')

plt.subplot(1,3,3)
plt.imshow(denoised, cmap='gray')
plt.title("Noise Reduced Image")
plt.axis('off')

plt.show()

# Step 5: Explanation
print("IMAGE ACQUISITION AND NOISE")
print("--------------------------------")
print("Original Image : Clean image without sensor noise.")
print("Noisy Image    : Gaussian noise added during image acquisition.")
print("Denoised Image : Gaussian Blur reduces noise while preserving the image.")

print("\nCauses of Noise During Image Acquisition:")
print("- Electronic sensor noise")
print("- Low light conditions")
print("- High camera ISO settings")
print("- Thermal noise in the sensor")

print("\nNoise Minimization:")
print("- Use Gaussian Blur or Median Filter")
print("- Improve lighting conditions")
print("- Use high-quality image sensors")
print("- Reduce sensor temperature")
