# -*- coding: utf-8 -*-
"""CV-CO1-AT1-Q10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v4xuDl7rwzTfvAJOE9Jp8h-PuW1H_SF_
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# -------------------------------
# Step 1: Create a High-Resolution Image
# -------------------------------
image = np.ones((512, 512, 3), dtype=np.uint8) * 255

# Draw objects
cv2.rectangle(image, (80, 80), (180, 180), (255, 0, 0), -1)      # Blue square
cv2.circle(image, (350, 150), 50, (0, 255, 0), -1)               # Green circle
cv2.putText(image, "CAR", (250, 350),
            cv2.FONT_HERSHEY_SIMPLEX, 2, (0, 0, 255), 4)

# -------------------------------
# Step 2: Reduce Sampling (Low Resolution)
# -------------------------------
low_res = cv2.resize(image, (128, 128), interpolation=cv2.INTER_AREA)

# Enlarge again to visualize pixel loss
low_res_up = cv2.resize(low_res, (512, 512), interpolation=cv2.INTER_NEAREST)

# -------------------------------
# Step 3: Display Images
# -------------------------------
plt.figure(figsize=(15,5))

plt.subplot(1,2,1)
plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
plt.title("High Resolution Image")
plt.axis("off")

plt.subplot(1,2,2)
plt.imshow(cv2.cvtColor(low_res_up, cv2.COLOR_BGR2RGB))
plt.title("Low Resolution Image")
plt.axis("off")

plt.show()

# -------------------------------
# Step 4: Explanation
# -------------------------------
print("OBJECT VISIBILITY USING SAMPLING")
print("--------------------------------------")
print("High Resolution Image:")
print("- More pixels capture finer object details.")
print("- Objects are sharp and clearly visible.")

print("\nLow Resolution Image:")
print("- Fewer pixels reduce image detail.")
print("- Small objects become blurred or pixelated.")
print("- Text and edges become difficult to recognize.")

print("\nImage Formation:")
print("- Camera quality, focus, and lighting affect image clarity.")
print("- Poor image formation and low sampling reduce object visibility.")

print("\nConclusion:")
print("Higher sampling resolution and good image formation improve object detection accuracy.")
