# -*- coding: utf-8 -*-
"""CV-CO1-AT1-Q07

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1niP3SZQfdW4CyKYVMunXvzSbiVdqyOuw
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Step 1: Create a grayscale gradient image
height, width = 256, 512
image = np.tile(np.arange(256, dtype=np.uint8), (height, 2))

# Step 2: Quantization Function
def quantize(img, levels):
    step = 256 // levels
    return (img // step) * step

# Quantize the image to different intensity levels
img_256 = image                   # Original (256 Gray Levels)
img_16 = quantize(image, 16)      # 16 Gray Levels
img_4 = quantize(image, 4)        # 4 Gray Levels

# Step 3: Display Images
plt.figure(figsize=(15,5))

plt.subplot(1,3,1)
plt.imshow(img_256, cmap='gray', vmin=0, vmax=255)
plt.title("Original (256 Gray Levels)")
plt.axis('off')

plt.subplot(1,3,2)
plt.imshow(img_16, cmap='gray', vmin=0, vmax=255)
plt.title("Quantized (16 Gray Levels)")
plt.axis('off')

plt.subplot(1,3,3)
plt.imshow(img_4, cmap='gray', vmin=0, vmax=255)
plt.title("Quantized (4 Gray Levels)")
plt.axis('off')

plt.show()

# Step 4: Explanation
print("GRAYSCALE TO DIGITAL IMAGE USING QUANTIZATION")
print("------------------------------------------------")
print("Original Image : 256 gray levels (8-bit).")
print("16-Level Image : Moderate image detail is preserved.")
print("4-Level Image  : Significant loss of detail with visible banding.")
print()
print("Role of Quantization:")
print("- Converts continuous intensity values into discrete digital levels.")
print("- Reduces storage requirements.")
print("- Lower quantization levels reduce image quality and fine details.")
