# -*- coding: utf-8 -*-
"""CO1-AT1-Q03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QjlKTqfvFBicAjQBw6j9ctXRQo1HTiTG
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Step 1: Create a high-frequency checkerboard image
size = 512
tile = 8

image = np.zeros((size, size), dtype=np.uint8)

for i in range(0, size, tile):
    for j in range(0, size, tile):
        if ((i // tile) + (j // tile)) % 2 == 0:
            image[i:i+tile, j:j+tile] = 255

# Step 2: Downsample without filtering (Aliasing)
alias_image = image[::4, ::4]

# Step 3: Corrective approach - Apply Gaussian Blur before downsampling
blurred = cv2.GaussianBlur(image, (7, 7), 1.5)
corrected = blurred[::4, ::4]

# Step 4: Display Results
plt.figure(figsize=(15,5))

plt.subplot(1,3,1)
plt.imshow(image, cmap='gray')
plt.title("Original High-Frequency Image")
plt.axis('off')

plt.subplot(1,3,2)
plt.imshow(alias_image, cmap='gray')
plt.title("Aliasing Artifact")
plt.axis('off')

plt.subplot(1,3,3)
plt.imshow(corrected, cmap='gray')
plt.title("Corrected (Gaussian Blur + Sampling)")
plt.axis('off')

plt.show()

# Explanation
print("CAUSE OF ALIASING")
print("-----------------")
print("Aliasing occurs because the image is sampled below the Nyquist rate.")
print("High-frequency details fold into lower frequencies, creating jagged patterns.")

print("\nQUANTIZATION")
print("------------")
print("Quantization converts pixel values into discrete intensity levels.")
print("It mainly affects brightness precision but is not the primary cause of aliasing.")

print("\nCORRECTIVE APPROACH")
print("------------------")
print("Apply a low-pass (Gaussian) filter before downsampling.")
print("This removes high-frequency components and reduces aliasing artifacts.")
