# -*- coding: utf-8 -*-
"""CV-CO1-AT1-Q05

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tO7qJV3NFymk6MkZ3xP1aRy5T524Djm6
"""

# Install OpenCV (only needed in Google Colab)
!pip install opencv-python-headless

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Create a blank frame (surveillance scene)
frame = np.zeros((400, 600, 3), dtype=np.uint8)

# Draw a person (represented by a rectangle)
cv2.rectangle(frame, (250, 100), (350, 300), (0, 255, 0), -1)

# Draw a camera label
cv2.putText(frame, "Surveillance Camera", (150, 40),
            cv2.FONT_HERSHEY_SIMPLEX, 1, (255,255,255), 2)

# Simulate object detection by drawing a bounding box
detected = frame.copy()
cv2.rectangle(detected, (250, 100), (350, 300), (0, 0, 255), 3)
cv2.putText(detected, "Person Detected", (220, 90),
            cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0,0,255), 2)

# Display Images
plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
plt.imshow(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
plt.title("Input Surveillance Frame")
plt.axis("off")

plt.subplot(1,2,2)
plt.imshow(cv2.cvtColor(detected, cv2.COLOR_BGR2RGB))
plt.title("Detected Person")
plt.axis("off")

plt.show()

# Classification Output
print("REAL-TIME SURVEILLANCE SYSTEM")
print("--------------------------------------")
print("Computer Vision Level : HIGH-LEVEL VISION")
print()
print("Reason:")
print("- Detects and recognizes objects (person).")
print("- Interprets scene information.")
print("- Makes intelligent decisions from images.")
print("- Suitable for security and surveillance applications.")
