# -*- coding: utf-8 -*-
"""CV-CO1-AT1-Q06

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uKe77FqPkMC0egpivZc3_c0c4npCk3aO
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Create a synthetic road image
img = np.zeros((400, 600, 3), dtype=np.uint8)

# Sky
img[:] = (180, 220, 255)

# Road
cv2.rectangle(img, (150, 0), (450, 400), (60, 60, 60), -1)

# Lane markings
for y in range(0, 400, 40):
    cv2.line(img, (300, y), (300, y+20), (255, 255, 255), 4)

# Simulate fog (image degradation)
fog = np.full_like(img, 180)
foggy = cv2.addWeighted(img, 0.5, fog, 0.5, 0)

# Improve image quality using Histogram Equalization
gray = cv2.cvtColor(foggy, cv2.COLOR_BGR2GRAY)
enhanced = cv2.equalizeHist(gray)

# Display Results
plt.figure(figsize=(15,5))

plt.subplot(1,3,1)
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.title("Original Road Image")
plt.axis("off")

plt.subplot(1,3,2)
plt.imshow(cv2.cvtColor(foggy, cv2.COLOR_BGR2RGB))
plt.title("Foggy Image")
plt.axis("off")

plt.subplot(1,3,3)
plt.imshow(enhanced, cmap="gray")
plt.title("Enhanced Image")
plt.axis("off")

plt.show()

# Explanation
print("IMAGE FORMATION MODEL IN AUTONOMOUS DRIVING")
print("-------------------------------------------")
print("Original Image : Clear road scene.")
print("Foggy Image    : Visibility reduced due to atmospheric effects.")
print("Enhanced Image : Histogram Equalization improves contrast.")
print()
print("Application:")
print("- Enhances road visibility.")
print("- Makes lane markings easier to detect.")
print("- Improves obstacle and vehicle detection.")
print("- Increases safety in autonomous driving.")
