# -*- coding: utf-8 -*-
"""CV-CO1-AT1-Q04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NI1C4HN4-I6fMZl2dxV882iq0JiUBAm4
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Create a synthetic medical-like grayscale image
size = 512
image = np.zeros((size, size), dtype=np.uint8)

# Draw circles to simulate organs/tissues
cv2.circle(image, (256, 256), 150, 180, -1)
cv2.circle(image, (256, 256), 80, 230, -1)
cv2.circle(image, (180, 180), 30, 120, -1)
cv2.circle(image, (340, 320), 25, 80, -1)

# ----------------------------
# Pixel Resolution Demonstration
# ----------------------------

# Low pixel resolution (downsample then upsample)
low_pixel = cv2.resize(image, (128, 128), interpolation=cv2.INTER_AREA)
low_pixel = cv2.resize(low_pixel, (512, 512), interpolation=cv2.INTER_NEAREST)

# ----------------------------
# Intensity Resolution Demonstration
# ----------------------------

# Reduce intensity resolution from 8-bit (256 levels) to 4-bit (16 levels)
levels = 16
low_intensity = (image // (256 // levels)) * (256 // levels)

# ----------------------------
# Display Results
# ----------------------------

plt.figure(figsize=(15,5))

plt.subplot(1,3,1)
plt.imshow(image, cmap='gray')
plt.title("Original Image\n512×512, 256 Gray Levels")
plt.axis('off')

plt.subplot(1,3,2)
plt.imshow(low_pixel, cmap='gray')
plt.title("Reduced Pixel Resolution")
plt.axis('off')

plt.subplot(1,3,3)
plt.imshow(low_intensity, cmap='gray')
plt.title("Reduced Intensity Resolution")
plt.axis('off')

plt.show()

# ----------------------------
# Explanation
# ----------------------------

print("IMAGE REPRESENTATION ANALYSIS")
print("--------------------------------")
print("Original Image:")
print("- High pixel resolution preserves fine anatomical details.")
print("- 256 gray levels provide smooth intensity transitions.\n")

print("Reduced Pixel Resolution:")
print("- Spatial details become blurred or blocky.")
print("- Small structures are difficult to identify.\n")

print("Reduced Intensity Resolution:")
print("- Only 16 gray levels are available.")
print("- Banding occurs, reducing tissue contrast.\n")

print("Medical Imaging Application:")
print("- High Pixel Resolution helps detect tiny abnormalities like tumors or fractures.")
print("- High Intensity Resolution helps distinguish soft tissues with similar brightness.")
